### ISSUE TITLE
Edit Landing Page

### ISSUE THREAD

**Issue by jerry1100** [whats-happening-uhm/whats-happening-uhm#22]
- Add more info to landing page (make it similar to GitHub's page (in incognito mode): https://github.com/

**Comment by dtokita** [comment]
I wouldn't close this issue yet, since there are a ton of things that still can be improved. However, for this Milestone I feel like this may be sufficient. One thing to add would be the links to the cards. Also find a way to recognize a sign up vs a sign in.
