### ISSUE TITLE
Disable submit action when 'enter' is pressed on add-event pages 1 and 2

### ISSUE THREAD

**Issue by jerry1100** [whats-happening-uhm/whats-happening-uhm#50]
Pressing enter will cause the form to be submitted. This can lead to users accidentally submitting events early.

Here's an example:
You're on a dropdown and you press enter thinking you're going to select the dropdown item. Instead, the form treats the `enter` as a form submission.

To fix:
Prevent `enter` from being registered as a 'submit' and have the user manually click the submit button to submit.

**Comment by glennga** [comment]
fixed.  <script>
    $("form").bind("keypress", function (e) {
      if (e.keyCode == 13) {
        $("#btnSearch").attr('value');
        //add more buttons here
        return false;
      }
    });
  </script>

**Comment by glennga** [comment]
*in issue 51
