### ISSUE TITLE
Play around with landing spinners

### ISSUE THREAD

**Issue by jerry1100** [whats-happening-uhm/whats-happening-uhm#59]
![image](https://cloud.githubusercontent.com/assets/18181641/25870816/35a429b6-34a1-11e7-923a-4f79b792f754.png)
http://stackoverflow.com/questions/17728386/meteor-findone-query-returns-undefined-in-one-template-helper-in-other-template

**Comment by glennga** [comment]
Unable to implement with given deadline.
